name: JavaScript
on:
  pull_request:
    paths:
      - "webpack/**"
      - "package.json"
      - ".github/workflows/js_tests.yml"
      - ".eslintrc"
      - ".eslintignore"

permissions:
  contents: read

jobs:
  test:
    permissions:
      checks: write # for coverallsapp/github-action to create new checks
      contents: read # for actions/checkout to fetch code
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Checkout Foreman
        uses: actions/checkout@v3
      - name: Setup Bun Runtime
        uses: antongolub/action-setup-bun@v1
        with:
          bun-repo: "oven-sh/bun"
          bun-version: ">=0.1"
          bun-config: '{"logLevel": "debug"}'
      - name: Install node modules
        run: bun install --force --verbose
      - name: Install @theforeman/test dependencies
        run: |
          cd node_modules/@theforeman/test
          bun install --force --verbose
      - name: Run linter
        run: bun run lint
      - name: Run Spellcheck (only warnings)
        run: bun run lint:spelling
      - name: Run tests
        run: bun run test
      - name: Publish Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
