name: (non-blocking) React on plugins

on:
  pull_request:
    branches: [develop]
    paths:
      - 'webpack/**'
      - 'package.json'
      - 'config/webpack.config.js'
      - '.github/workflows/plugins_react_tests.yml'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        include:
          - repo: katello
            org: Katello
          - repo: foreman-tasks
            org: theforeman
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 6
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Checkout Foreman
        uses: actions/checkout@v3
        with:
          path: ./projects/foreman
      - name: Install dependencies
        run: pnpm recursive install
        working-directory: ${{ github.workspace }}/projects/foreman
      - name: Checkout ${{ matrix.repo }}
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.org }}/${{ matrix.repo }}
          path: ./projects/${{ matrix.repo }}
      - name: Install ${{ matrix.repo }} npm dependencies
        run: pnpm recursive install
        working-directory: ${{ github.workspace }}/projects/${{ matrix.repo }}
      - name: Run ${{ matrix.plugin_repo }} tests
        run: pnpm test
        working-directory: ${{ github.workspace }}/projects/${{ matrix.repo }}
